### ISSUE TITLE
Timing Attack Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [RNCryptor/RNCryptor-cpp#2]
http://www.openwall.com/lists/oss-security/2016/01/24/10
- https://github.com/RNCryptor/RNCryptor-Spec/blob/04378bc27c604e97353badbead8c435698abe97a/RNCryptor-Spec-v3.md#consistent-time-equality-checking
- https://cryptocoding.net/index.php/Coding_rules#Compare_secret_strings_in_constant_time
- http://blog.ircmaxell.com/2014/11/its-all-about-time.html

Problematic line: https://github.com/RNCryptor/RNCryptor-cpp/blob/c7eba4afa398f54b97f0a60e42806bf373c89316/src/rndecryptor.cpp#L98

**Comment by curtisdf** [comment]
Thanks @paragonie-scott.  Pull requests are welcome. C++ is far from my area of expertise. I don't really know what would be the "best practice" way of implementing a constant-time comparison in this language.
